version: '3.8'

services:
  web:
    build: .
    ports:
      - "8001:8001"
    volumes:
      - .:/rails
      - bundle_cache:/usr/local/bundle
    environment:
      - RAILS_ENV=development
    command: ./bin/rails server -b 0.0.0.0 -p 8001

volumes:
  bundle_cache: 