version: '3.8'

services:
  todo-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    restart: unless-stopped 